### ISSUE TITLE
[BUG] The playlist icon is not displayed in the latest version of spotify.

### ISSUE THREAD

**Issue by Lseoksee** [JulienMaille/dribbblish-dynamic-theme#73]
**Describe the bug**
The playlist icon is not displayed in the 1.1.70.610 of spotify.

**To Reproduce**
main screen spotify.

**Screenshots**
originally
![image2](https://user-images.githubusercontent.com/91320047/137579092-d2e8291e-58a0-4ba4-aa9f-3fa53f1c1639.png)
dribbblish dynamic
 -normally
![w](https://user-images.githubusercontent.com/91320047/137579417-1f87c704-104f-4c02-8eda-6a0cd1828b1a.png)
 -push button
![sd](https://user-images.githubusercontent.com/91320047/137579306-74fb6297-f418-4979-8e6f-943b961dea8b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: spotify 1.1.70.610  spicetify 2.7.1

**Comment by JulienMaille** [comment]
I think this results from a combination of spotify update (which broke the css once again) and this style (from the original Dribbblish theme) :
https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/653ed6481484a3337447a630cf4ac458b0fd1dbe/user.css#L503-L504

**Comment by SendNukez** [comment]
1.1.70 also makes friends' profile pictures bigger
```css
.main-avatar-avatar > div {
    width: 100% !important;
    height: 100% !important;
}
```
should fix it, but there is probably even more things that were broken.

**Comment by JulienMaille** [comment]
This is a never ending process, Spotify will break stuff every week

**Comment by Lseoksee** [comment]
> I think I know what the root of this entire issue is. It is not Spotify but more or so it is Spicetify 2.7.1 that breaks the theme. On Spicetify 2.7.0 with Spotify being updated to version 1.1.70 it worked perfectly but once it is upgraded to 2.7.1 that is what breaks the entire theme

The phenomenon that the playlist icon is not displayed seems to persist even in Specific 2.7.1

**Comment by Lseoksee** [comment]
> I dont think the main issue is the playlist icon but more or so on a wider scale about how Spicetify 2.7.1 is breaking the entire theme. I am currently on the Windows version of Spotify 1.1.70 and I can attach a screenshot of how it looks currently with Spicetify 2.7.0 in place. @JulienMaille

Do you use Windows 10? I tried to reinstall Spotify, but there is still a problem. I think it's also a problem with Windows 11.

**Comment by SendNukez** [comment]
I added a fix for this. But its not the best solution since this is likely caused by the css-map in Spicetify.

**Comment by JulienMaille** [comment]
Was the workaround removed a while ago?

**Comment by SendNukez** [comment]
I actually put the comment in the wrong place. The workaround is the code above the comment, the `& span` part. The issue still consists, but I think we can just keep it since I'm guessing this was part of some Spotify update rather than a "broken" css map. Specifically, I think the playlist icon became a `.GlueDropTarget`, which is why
```css
html.sidebar-hide-text .GlueDropTarget span,
html.sidebar-hide-text .main-navBar-navBarItem span,
html.sidebar-hide-text .main-rootlist-rootlistContent span,
html.sidebar-hide-text .main-rootlist-rootlistItem span {
    display: none;
}
```
now applies to it.
